---
scrape_configs:
  - job_name: otel-proxy.localhost
    static_configs:
      - targets:
          - 127.0.0.53:6318
  - job_name: loki.localhost
    static_configs:
      - targets:
          - 127.0.0.53:3100
