---
services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    labels:
      kompose.controller.type: statefulset
      kompose.service.expose: bt.${DOMAIN}
    ports:
      - 9696
    volumes:
      - /var/lib/local/prowlarr:/config
