---
services:
  mongo_express:
    image: docker.io/library/mongo-express:latest
    labels:
      kompose.service.expose: mongo.${DOMAIN}
      # - traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}
      # - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}.headers.customRequestHeaders.Authorization=Basic YWRtaW46cGFzcw==
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${COMPOSE_PROJECT_NAME}:${COMPOSE_PROJECT_NAME}@mongo:27017/
    ports:
      - 8081
    volumes:
      - /usr/local/opt/${COMPOSE_PROJECT_NAME}/conf.yml:/invidious/config/config.yml:ro

  mongo:
    image: docker.io/library/mongo:latest
    labels:
      kompose.controller.type: statefulset
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${COMPOSE_PROJECT_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${COMPOSE_PROJECT_NAME}
    ports:
      - 127.0.0.53:27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
