---
services:
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    labels:
      kompose.service.expose: redis.${DOMAIN}
    environment:
      ADDRESS: "::"
      REDIS_HOSTS: lo:redis:6379:0:${COMPOSE_PROJECT_NAME}
    ports:
      - 8081

  redis:
    image: ghcr.io/valkey-io/valkey:latest
    labels:
      kompose.service.type: nodeport
      kompose.service.nodeport.port: m5_esyscmd([printf -- %s '30000 + 6379 % 2767' | bc])
    healthcheck:
      test:
        - CMD
        - redis-cli
        - incr
        - ping
    command:
      - redis-server
      # - --requirepass
      # - ${COMPOSE_PROJECT_NAME}
    ports:
      - 6379
    volumes:
      - data:/data

  # mcp:
  #   image: docker.io/mcp/redis:latest
  #   # labels:
  #     # kompose.service.expose: mcp-redis.${DOMAIN}
  #   environment:
  #     REDIS_HOST: redis
  #   ports:
  #     - 8080

volumes:
  data:
