[Server]
hostname = "twitter.m5_assert([ENV_DOMAIN])"
https    = true
title    = "ğŸ“"

[Cache]
redisHost = "nitter-redis"

[Preferences]
replaceReddit  = "libreddit.m5_assert([ENV_DOMAIN])"
replaceTwitter = "nitter.m5_assert([ENV_DOMAIN])"
replaceYouTube = "invidious.m5_assert([ENV_DOMAIN])"

hlsPlayback    = true
infiniteScroll = true
theme          = "Auto"
