[Server]
hostname = "twitter.m5_assert([ENV_DOMAIN])"
https    = true
title    = "ğŸ“"

[Cache]
redisHost = "redis"

[Preferences]
replaceReddit  = "reddit.m5_assert([ENV_DOMAIN])"
replaceTwitter = "twitter.m5_assert([ENV_DOMAIN])"
replaceYouTube = "youtube.m5_assert([ENV_DOMAIN])"

hlsPlayback    = true
infiniteScroll = true
theme          = "Auto"
