---
services:
  phpmyadmin:
    image: docker.io/library/phpmyadmin:latest
    labels:
      kompose.service.expose: mysql.${DOMAIN}
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: ${COMPOSE_PROJECT_NAME}
      PMA_USER: root
    ports:
      - 80

  mysql:
    image: docker.io/library/mysql:latest
    labels:
      kompose.controller.type: statefulset
    environment:
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
      MYSQL_PASSWORD: ${COMPOSE_PROJECT_NAME}
      MYSQL_ROOT_PASSWORD: ${COMPOSE_PROJECT_NAME}
      MYSQL_USER: ${COMPOSE_PROJECT_NAME}
    ports:
      - 3306
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
