---
services:
  anubis:
    image: ghcr.io/techarohq/anubis:main
    labels:
      kompose.service.expose: twitter.${DOMAIN}
    environment:
      COOKIE_DOMAIN: ${DOMAIN}
      ED25519_PRIVATE_KEY_HEX: m5_esyscmd([printf -- %s 'DOMAIN' | b3sum | cut -d ' ' -f 1])
      SERVE_ROBOTS_TXT: true
      TARGET: http://nitter:8080
    ports:
      - 8923

  nitter:
    image: docker.io/zedeus/nitter:latest
    ports:
      - 8080
    volumes:
      - ./nitter.toml:/src/nitter.conf:ro
      - ./sessions.jsonl:/src/sessions.jsonl:ro

  redis:
    image: ghcr.io/valkey-io/valkey:latest
    ports:
      - 6379
    volumes:
      - data:/data

volumes:
  data:
