[[Server]]
hostname = "twitter.m5_assert([ENV_DOMAIN])"
https    = true
title    = "ğŸ“"

[[Cache]]
redisHost = "redis"

# [[Config]]
# proxy = ""

[[Preferences]]
hlsPlayback    = true
infiniteScroll = true
replaceReddit  = "old.reddit.com"
replaceTwitter = "twitter.m5_assert([ENV_DOMAIN])"
replaceYouTube = "youtube.m5_assert([ENV_DOMAIN])"
theme          = "Auto"
