[[Server]]
hostname = "weibo.m5_assert([ENV_DOMAIN])"
https    = true
title    = "üêì"

[[Cache]]
redisHost = "redis"

[[Config]]
proxy = "http://proxy.kompsed-hostproxy.svc.cluster.local:1080"

[[Preferences]]
hlsPlayback    = true
infiniteScroll = true
replaceReddit  = "old.reddit.com"
replaceTwitter = "weibo.m5_assert([ENV_DOMAIN])"
replaceYouTube = "youku.m5_assert([ENV_DOMAIN])"
theme          = "Auto"
