---
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:${VERSION}
    labels:
      kompose.controller.type: statefulset
      kompose.service.expose: kibana.${DOMAIN}
    environment:
      SERVER_NAME:
      ELASTICSEARCH_SSL_VERIFICATIONMODE: none
    ports:
      - 5601

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    mem_limit: 512M
    labels:
      kompose.controller.type: statefulset
      kompose.service.expose: elastic.${DOMAIN}
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    ports:
      - 9200
    volumes:
      - data:/usr/share/elasticsearch/data

  log:
    image: docker.elastic.co/logstash/logstash:${VERSION}
    mem_limit: 512M
    labels:
      kompose.service.expose: logstash.${DOMAIN}
    ports:
      - 9600

volumes:
  data:
