---
services:
  rclone:
    image: ghcr.io/rclone/rclone:latest
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME}2.loadbalancer.server.port=8080
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}2.rule=HostRegexp(`^minio\.`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}2.service=${COMPOSE_PROJECT_NAME}2
    command:
      - serve
      - webdav
      - --config=/dev/null
      - --dir-cache-time=0
      - --poll-interval=0
      - --addr=:8080
      - --
      - /data
    volumes:
      - /var/lib/local/rclone:/data
