---
services:
  thirteen-ft:
    image: ghcr.io/wasi-master/13ft:latest
    labels:
      kompose.service.expose: 12ft.${DOMAIN}
    environment:
      HTTP_PROXY: http://proxy.kompsed-hostproxy.svc.cluster.local:1080
    ports:
      - 5000
