---
services:
  cloudbeaver:
    image: docker.io/dbeaver/cloudbeaver:latest
    labels:
      kompose.controller.type: statefulset
      kompose.service.expose: sql.${DOMAIN}
      kompose.volume.type: hostPath
    ports:
      - 8978
    volumes:
      - /var/lib/local/cloudbeaver:/opt/cloudbeaver/workspace
