---
services:
  phpmyadmin:
    image: docker.io/dpage/pgadmin4:latest
    labels:
      kompose.service.expose: pgadmin.${DOMAIN}
    environment:
      WEBSERVER_AUTO_CREATE_USER:
      WEBSERVER_REMOTE_USER: X-Forwarded-User
    ports:
      - 80

  pg:
    image: docker.io/library/postgres:latest
    environment:
      POSTGRES_DB: ${COMPOSE_PROJECT_NAME}
      POSTGRES_PASSWORD: ${COMPOSE_PROJECT_NAME}
      POSTGRES_USER: ${COMPOSE_PROJECT_NAME}
    ports:
      - 5432
    volumes:
      - data:/var/lib/postgresql

  mcp:
    image: us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:latest
    labels:
      kompose.service.expose: mcp-postgres.${DOMAIN}
    command:
      - toolbox
      - "--address=::"
    ports:
      - 5000

volumes:
  data:
