---
services:
  otel-collector:
    labels:
      kompose.controller.type: statefulset
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    volumes:
      - ./conf.yml:/etc/otelcol-contrib/config.yaml:ro
      - data:/var/lib/otelcol-contrib

volumes:
  data:
