---
services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    labels:
      kompose.service.expose: link.${DOMAIN}
    environment:
      DATABASE_URL:
      DISABLE_NEW_SSO_USERS: true
      MEILI_MASTER_KEY:
      NEXT_PUBLIC_DISABLE_REGISTRATION: true
      NEXTAUTH_SECRET:
    ports:
      - 3000
    volumes:
      - data:/data/data

  meilisearch:
    image: docker.io/getmeili/meilisearch:latest
    environment:
      MEILI_MASTER_KEY:
    volumes:
      - search:/meili_data

volumes:
  data:
  search:
